import type { Metadata } from "next"
import "./globals.css"
import ClientLayout from "./components/ClientLayout"
import { JobProvider } from "@/context/JobContext"

export const metadata: Metadata = {
  title: "Job Board",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-white to-gray-100 min-h-screen"> 
         <JobProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </JobProvider>
      </body>
    </html>
  )
}